/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'cms-users': CmsUserAuthOperations;
  };
  blocks: {};
  collections: {
    'cms-users': CmsUser;
    pages: Page;
    posts: Post;
    categories: Category;
    tags: Tag;
    authors: Author;
    media: Media;
    navigation: Navigation;
    redirects: Redirect;
    'site-settings': SiteSetting;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'cms-users': CmsUsersSelect<false> | CmsUsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'platform-settings': PlatformSetting;
  };
  globalsSelect: {
    'platform-settings': PlatformSettingsSelect<false> | PlatformSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: CmsUser;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface CmsUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users".
 */
export interface CmsUser {
  id: number;
  name?: string | null;
  role: 'cms_admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'cms-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Auto-filled from CMS_DEFAULT_ORGANIZATION_ID or WEB_ORGANIZATION_ID for local editing.
   */
  organizationId: string;
  /**
   * Auto-filled from CMS_DEFAULT_WEBSITE_ID or WEB_WEBSITE_ID for local editing.
   */
  websiteId?: string | null;
  title: string;
  slug: string;
  workflowStatus: 'draft' | 'review' | 'published' | 'archived';
  featuredImage?: (number | null) | Media;
  author?: (number | null) | Author;
  publishDate?: string | null;
  /**
   * Future publish time. Publishing automation will be wired in a later milestone.
   */
  scheduledPublishAt?: string | null;
  previewUrl?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    socialImage?: (number | null) | Media;
    openGraph?: {
      title?: string | null;
      description?: string | null;
      type?: ('website' | 'article') | null;
    };
    twitterCard?: ('summary' | 'summary_large_image') | null;
    robots?: {
      index?: boolean | null;
      follow?: boolean | null;
    };
    /**
     * Structured data placeholder for future SEO automation.
     */
    schema?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Compose this page using registered Starter Website Kit sections. The website renderer resolves these block types through the frontend Block Registry.
   */
  layout?:
    | (
        | {
            badge?: string | null;
            headline: string;
            subheadline?: string | null;
            primaryCta?: {
              label?: string | null;
              url?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              url?: string | null;
            };
            backgroundImage?: {
              media?: (number | null) | Media;
              url?: string | null;
              alt?: string | null;
            };
            videoBackgroundUrl?: string | null;
            heroImage?: {
              media?: (number | null) | Media;
              url?: string | null;
              alt?: string | null;
            };
            trustIndicators?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Future block-specific rendering settings.
             */
            settings?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            /**
             * Optional block-level theme overrides consumed by the renderer.
             */
            theme?: {
              background?: string | null;
              colorMode?: ('system' | 'light' | 'dark') | null;
              containerWidth?: string | null;
              spacing?: string | null;
            };
            /**
             * Future conditional visibility rules.
             */
            visibility?:
              | {
                  field: string;
                  operator: 'equals' | 'not_equals' | 'exists';
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Future responsive controls. Stored as JSON until the visual builder ships.
             */
            responsive?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            animation?: {
              enabled?: boolean | null;
              preset?: ('none' | 'fade' | 'slide' | 'scale') | null;
              durationMs?: number | null;
              delayMs?: number | null;
            };
            seo?: {
              isPrimaryHeading?: boolean | null;
              includeInTableOfContents?: boolean | null;
              noIndexSection?: boolean | null;
              structuredDataType?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            headline: string;
            carouselReady?: boolean | null;
            logos?:
              | {
                  name: string;
                  image?: {
                    media?: (number | null) | Media;
                    url?: string | null;
                    alt?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            /**
             * Future block-specific rendering settings.
             */
            settings?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            /**
             * Optional block-level theme overrides consumed by the renderer.
             */
            theme?: {
              background?: string | null;
              colorMode?: ('system' | 'light' | 'dark') | null;
              containerWidth?: string | null;
              spacing?: string | null;
            };
            /**
             * Future conditional visibility rules.
             */
            visibility?:
              | {
                  field: string;
                  operator: 'equals' | 'not_equals' | 'exists';
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Future responsive controls. Stored as JSON until the visual builder ships.
             */
            responsive?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            animation?: {
              enabled?: boolean | null;
              preset?: ('none' | 'fade' | 'slide' | 'scale') | null;
              durationMs?: number | null;
              delayMs?: number | null;
            };
            seo?: {
              isPrimaryHeading?: boolean | null;
              includeInTableOfContents?: boolean | null;
              noIndexSection?: boolean | null;
              structuredDataType?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'logo-cloud';
          }
        | {
            eyebrow?: string | null;
            headline: string;
            text?: string | null;
            items?:
              | {
                  icon?: string | null;
                  title: string;
                  description: string;
                  link: {
                    label: string;
                    url: string;
                    id?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            /**
             * Future block-specific rendering settings.
             */
            settings?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            /**
             * Optional block-level theme overrides consumed by the renderer.
             */
            theme?: {
              background?: string | null;
              colorMode?: ('system' | 'light' | 'dark') | null;
              containerWidth?: string | null;
              spacing?: string | null;
            };
            /**
             * Future conditional visibility rules.
             */
            visibility?:
              | {
                  field: string;
                  operator: 'equals' | 'not_equals' | 'exists';
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Future responsive controls. Stored as JSON until the visual builder ships.
             */
            responsive?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            animation?: {
              enabled?: boolean | null;
              preset?: ('none' | 'fade' | 'slide' | 'scale') | null;
              durationMs?: number | null;
              delayMs?: number | null;
            };
            seo?: {
              isPrimaryHeading?: boolean | null;
              includeInTableOfContents?: boolean | null;
              noIndexSection?: boolean | null;
              structuredDataType?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            headline: string;
            text?: string | null;
            items?:
              | {
                  image?: {
                    media?: (number | null) | Media;
                    url?: string | null;
                    alt?: string | null;
                  };
                  title: string;
                  description: string;
                  cta?: {
                    label?: string | null;
                    url?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            /**
             * Future block-specific rendering settings.
             */
            settings?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            /**
             * Optional block-level theme overrides consumed by the renderer.
             */
            theme?: {
              background?: string | null;
              colorMode?: ('system' | 'light' | 'dark') | null;
              containerWidth?: string | null;
              spacing?: string | null;
            };
            /**
             * Future conditional visibility rules.
             */
            visibility?:
              | {
                  field: string;
                  operator: 'equals' | 'not_equals' | 'exists';
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Future responsive controls. Stored as JSON until the visual builder ships.
             */
            responsive?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            animation?: {
              enabled?: boolean | null;
              preset?: ('none' | 'fade' | 'slide' | 'scale') | null;
              durationMs?: number | null;
              delayMs?: number | null;
            };
            seo?: {
              isPrimaryHeading?: boolean | null;
              includeInTableOfContents?: boolean | null;
              noIndexSection?: boolean | null;
              structuredDataType?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            headline: string;
            text?: string | null;
            animated?: boolean | null;
            items?:
              | {
                  value: number;
                  suffix?: string | null;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Future block-specific rendering settings.
             */
            settings?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            /**
             * Optional block-level theme overrides consumed by the renderer.
             */
            theme?: {
              background?: string | null;
              colorMode?: ('system' | 'light' | 'dark') | null;
              containerWidth?: string | null;
              spacing?: string | null;
            };
            /**
             * Future conditional visibility rules.
             */
            visibility?:
              | {
                  field: string;
                  operator: 'equals' | 'not_equals' | 'exists';
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Future responsive controls. Stored as JSON until the visual builder ships.
             */
            responsive?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            animation?: {
              enabled?: boolean | null;
              preset?: ('none' | 'fade' | 'slide' | 'scale') | null;
              durationMs?: number | null;
              delayMs?: number | null;
            };
            seo?: {
              isPrimaryHeading?: boolean | null;
              includeInTableOfContents?: boolean | null;
              noIndexSection?: boolean | null;
              structuredDataType?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'statistics';
          }
        | {
            headline: string;
            text?: string | null;
            items?:
              | {
                  avatar?: {
                    media?: (number | null) | Media;
                    url?: string | null;
                    alt?: string | null;
                  };
                  rating?: number | null;
                  quote: string;
                  name: string;
                  company?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Future block-specific rendering settings.
             */
            settings?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            /**
             * Optional block-level theme overrides consumed by the renderer.
             */
            theme?: {
              background?: string | null;
              colorMode?: ('system' | 'light' | 'dark') | null;
              containerWidth?: string | null;
              spacing?: string | null;
            };
            /**
             * Future conditional visibility rules.
             */
            visibility?:
              | {
                  field: string;
                  operator: 'equals' | 'not_equals' | 'exists';
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Future responsive controls. Stored as JSON until the visual builder ships.
             */
            responsive?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            animation?: {
              enabled?: boolean | null;
              preset?: ('none' | 'fade' | 'slide' | 'scale') | null;
              durationMs?: number | null;
              delayMs?: number | null;
            };
            seo?: {
              isPrimaryHeading?: boolean | null;
              includeInTableOfContents?: boolean | null;
              noIndexSection?: boolean | null;
              structuredDataType?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            headline: string;
            text?: string | null;
            plans?:
              | {
                  name: string;
                  description?: string | null;
                  price: string;
                  highlighted?: boolean | null;
                  features?:
                    | {
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  cta?: {
                    label?: string | null;
                    url?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            /**
             * Future block-specific rendering settings.
             */
            settings?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            /**
             * Optional block-level theme overrides consumed by the renderer.
             */
            theme?: {
              background?: string | null;
              colorMode?: ('system' | 'light' | 'dark') | null;
              containerWidth?: string | null;
              spacing?: string | null;
            };
            /**
             * Future conditional visibility rules.
             */
            visibility?:
              | {
                  field: string;
                  operator: 'equals' | 'not_equals' | 'exists';
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Future responsive controls. Stored as JSON until the visual builder ships.
             */
            responsive?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            animation?: {
              enabled?: boolean | null;
              preset?: ('none' | 'fade' | 'slide' | 'scale') | null;
              durationMs?: number | null;
              delayMs?: number | null;
            };
            seo?: {
              isPrimaryHeading?: boolean | null;
              includeInTableOfContents?: boolean | null;
              noIndexSection?: boolean | null;
              structuredDataType?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            headline: string;
            text?: string | null;
            categoriesEnabled?: boolean | null;
            items?:
              | {
                  category?: string | null;
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Future block-specific rendering settings.
             */
            settings?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            /**
             * Optional block-level theme overrides consumed by the renderer.
             */
            theme?: {
              background?: string | null;
              colorMode?: ('system' | 'light' | 'dark') | null;
              containerWidth?: string | null;
              spacing?: string | null;
            };
            /**
             * Future conditional visibility rules.
             */
            visibility?:
              | {
                  field: string;
                  operator: 'equals' | 'not_equals' | 'exists';
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Future responsive controls. Stored as JSON until the visual builder ships.
             */
            responsive?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            animation?: {
              enabled?: boolean | null;
              preset?: ('none' | 'fade' | 'slide' | 'scale') | null;
              durationMs?: number | null;
              delayMs?: number | null;
            };
            seo?: {
              isPrimaryHeading?: boolean | null;
              includeInTableOfContents?: boolean | null;
              noIndexSection?: boolean | null;
              structuredDataType?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            backgroundVariant?: ('default' | 'muted' | 'contrast') | null;
            headline: string;
            text?: string | null;
            buttons?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Future block-specific rendering settings.
             */
            settings?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            /**
             * Optional block-level theme overrides consumed by the renderer.
             */
            theme?: {
              background?: string | null;
              colorMode?: ('system' | 'light' | 'dark') | null;
              containerWidth?: string | null;
              spacing?: string | null;
            };
            /**
             * Future conditional visibility rules.
             */
            visibility?:
              | {
                  field: string;
                  operator: 'equals' | 'not_equals' | 'exists';
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Future responsive controls. Stored as JSON until the visual builder ships.
             */
            responsive?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            animation?: {
              enabled?: boolean | null;
              preset?: ('none' | 'fade' | 'slide' | 'scale') | null;
              durationMs?: number | null;
              delayMs?: number | null;
            };
            seo?: {
              isPrimaryHeading?: boolean | null;
              includeInTableOfContents?: boolean | null;
              noIndexSection?: boolean | null;
              structuredDataType?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            logo?: {
              media?: (number | null) | Media;
              url?: string | null;
              alt?: string | null;
            };
            navigation?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            socialLinks?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            copyright: string;
            contact?: string | null;
            /**
             * Future block-specific rendering settings.
             */
            settings?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            /**
             * Optional block-level theme overrides consumed by the renderer.
             */
            theme?: {
              background?: string | null;
              colorMode?: ('system' | 'light' | 'dark') | null;
              containerWidth?: string | null;
              spacing?: string | null;
            };
            /**
             * Future conditional visibility rules.
             */
            visibility?:
              | {
                  field: string;
                  operator: 'equals' | 'not_equals' | 'exists';
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Future responsive controls. Stored as JSON until the visual builder ships.
             */
            responsive?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            animation?: {
              enabled?: boolean | null;
              preset?: ('none' | 'fade' | 'slide' | 'scale') | null;
              durationMs?: number | null;
              delayMs?: number | null;
            };
            seo?: {
              isPrimaryHeading?: boolean | null;
              includeInTableOfContents?: boolean | null;
              noIndexSection?: boolean | null;
              structuredDataType?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'footer';
          }
        | {
            headline: string;
            text?: string | null;
            email?: string | null;
            phone?: string | null;
            /**
             * References a website form managed from the operations dashboard.
             */
            formId?: string | null;
            /**
             * Future block-specific rendering settings.
             */
            settings?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            /**
             * Optional block-level theme overrides consumed by the renderer.
             */
            theme?: {
              background?: string | null;
              colorMode?: ('system' | 'light' | 'dark') | null;
              containerWidth?: string | null;
              spacing?: string | null;
            };
            /**
             * Future conditional visibility rules.
             */
            visibility?:
              | {
                  field: string;
                  operator: 'equals' | 'not_equals' | 'exists';
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Future responsive controls. Stored as JSON until the visual builder ships.
             */
            responsive?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            animation?: {
              enabled?: boolean | null;
              preset?: ('none' | 'fade' | 'slide' | 'scale') | null;
              durationMs?: number | null;
              delayMs?: number | null;
            };
            seo?: {
              isPrimaryHeading?: boolean | null;
              includeInTableOfContents?: boolean | null;
              noIndexSection?: boolean | null;
              structuredDataType?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Auto-filled from CMS_DEFAULT_ORGANIZATION_ID or WEB_ORGANIZATION_ID for local editing.
   */
  organizationId: string;
  alt: string;
  caption?: string | null;
  /**
   * Logical folder path for media organization.
   */
  folderPath?: string | null;
  /**
   * Image focal point used by future responsive rendering.
   */
  focalPoint?: {
    /**
     * Horizontal focal position from 0 to 100.
     */
    x?: number | null;
    /**
     * Vertical focal position from 0 to 100.
     */
    y?: number | null;
  };
  /**
   * Provider metadata, EXIF-derived values, video duration, or PDF details.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * Auto-filled from CMS_DEFAULT_ORGANIZATION_ID or WEB_ORGANIZATION_ID for local editing.
   */
  organizationId: string;
  name: string;
  slug: string;
  email?: string | null;
  /**
   * Optional ID of the platform user this author profile represents.
   */
  userId?: string | null;
  avatar?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Auto-filled from CMS_DEFAULT_ORGANIZATION_ID or WEB_ORGANIZATION_ID for local editing.
   */
  organizationId: string;
  title: string;
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  author?: (number | null) | Author;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  /**
   * Estimated reading time in minutes.
   */
  readingTime?: number | null;
  relatedPosts?: (number | Post)[] | null;
  publishDate?: string | null;
  /**
   * Future publish time. Publishing automation will be wired in a later milestone.
   */
  scheduledPublishAt?: string | null;
  previewUrl?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    socialImage?: (number | null) | Media;
    openGraph?: {
      title?: string | null;
      description?: string | null;
      type?: ('website' | 'article') | null;
    };
    twitterCard?: ('summary' | 'summary_large_image') | null;
    robots?: {
      index?: boolean | null;
      follow?: boolean | null;
    };
    /**
     * Structured data placeholder for future SEO automation.
     */
    schema?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Auto-filled from CMS_DEFAULT_ORGANIZATION_ID or WEB_ORGANIZATION_ID for local editing.
   */
  organizationId: string;
  name: string;
  slug: string;
  description?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    socialImage?: (number | null) | Media;
    openGraph?: {
      title?: string | null;
      description?: string | null;
      type?: ('website' | 'article') | null;
    };
    twitterCard?: ('summary' | 'summary_large_image') | null;
    robots?: {
      index?: boolean | null;
      follow?: boolean | null;
    };
    /**
     * Structured data placeholder for future SEO automation.
     */
    schema?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Auto-filled from CMS_DEFAULT_ORGANIZATION_ID or WEB_ORGANIZATION_ID for local editing.
   */
  organizationId: string;
  name: string;
  slug: string;
  description?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    socialImage?: (number | null) | Media;
    openGraph?: {
      title?: string | null;
      description?: string | null;
      type?: ('website' | 'article') | null;
    };
    twitterCard?: ('summary' | 'summary_large_image') | null;
    robots?: {
      index?: boolean | null;
      follow?: boolean | null;
    };
    /**
     * Structured data placeholder for future SEO automation.
     */
    schema?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Auto-filled from CMS_DEFAULT_ORGANIZATION_ID or WEB_ORGANIZATION_ID for local editing.
   */
  organizationId: string;
  title: string;
  slug: string;
  location: 'header' | 'footer' | 'custom';
  items: {
    label: string;
    url?: string | null;
    page?: (number | null) | Page;
    openInNewTab?: boolean | null;
    children?:
      | {
          label: string;
          url?: string | null;
          page?: (number | null) | Page;
          openInNewTab?: boolean | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Auto-filled from CMS_DEFAULT_ORGANIZATION_ID or WEB_ORGANIZATION_ID for local editing.
   */
  organizationId: string;
  from: string;
  to: string;
  statusCode: '301' | '302';
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Auto-filled from CMS_DEFAULT_ORGANIZATION_ID or WEB_ORGANIZATION_ID for local editing.
   */
  organizationId: string;
  siteName: string;
  seo?: {
    siteTitle?: string | null;
    titleTemplate?: string | null;
    defaultMetaDescription?: string | null;
    canonicalBaseUrl?: string | null;
    defaultOgImage?: (number | null) | Media;
    siteName?: string | null;
    locale?: string | null;
    defaultRobots?: {
      index?: boolean | null;
      follow?: boolean | null;
    };
  };
  brand?: {
    logo?: (number | null) | Media;
    favicon?: (number | null) | Media;
    tagline?: string | null;
  };
  theme?: {
    primaryColor?: string | null;
    secondaryColor?: string | null;
    fontFamily?: string | null;
    borderRadius?: string | null;
    containerWidth?: string | null;
    mode?: ('system' | 'light' | 'dark') | null;
  };
  contactInformation?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  analytics?: {
    googleAnalyticsId?: string | null;
    googleTagManagerId?: string | null;
    metaPixelId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'cms-users';
        value: number | CmsUser;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'navigation';
        value: number | Navigation;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'cms-users';
    value: number | CmsUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'cms-users';
    value: number | CmsUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users_select".
 */
export interface CmsUsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  organizationId?: T;
  websiteId?: T;
  title?: T;
  slug?: T;
  workflowStatus?: T;
  featuredImage?: T;
  author?: T;
  publishDate?: T;
  scheduledPublishAt?: T;
  previewUrl?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        socialImage?: T;
        openGraph?:
          | T
          | {
              title?: T;
              description?: T;
              type?: T;
            };
        twitterCard?: T;
        robots?:
          | T
          | {
              index?: T;
              follow?: T;
            };
        schema?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              badge?: T;
              headline?: T;
              subheadline?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              backgroundImage?:
                | T
                | {
                    media?: T;
                    url?: T;
                    alt?: T;
                  };
              videoBackgroundUrl?: T;
              heroImage?:
                | T
                | {
                    media?: T;
                    url?: T;
                    alt?: T;
                  };
              trustIndicators?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              settings?: T;
              theme?:
                | T
                | {
                    background?: T;
                    colorMode?: T;
                    containerWidth?: T;
                    spacing?: T;
                  };
              visibility?:
                | T
                | {
                    field?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
              responsive?: T;
              animation?:
                | T
                | {
                    enabled?: T;
                    preset?: T;
                    durationMs?: T;
                    delayMs?: T;
                  };
              seo?:
                | T
                | {
                    isPrimaryHeading?: T;
                    includeInTableOfContents?: T;
                    noIndexSection?: T;
                    structuredDataType?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'logo-cloud'?:
          | T
          | {
              headline?: T;
              carouselReady?: T;
              logos?:
                | T
                | {
                    name?: T;
                    image?:
                      | T
                      | {
                          media?: T;
                          url?: T;
                          alt?: T;
                        };
                    id?: T;
                  };
              settings?: T;
              theme?:
                | T
                | {
                    background?: T;
                    colorMode?: T;
                    containerWidth?: T;
                    spacing?: T;
                  };
              visibility?:
                | T
                | {
                    field?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
              responsive?: T;
              animation?:
                | T
                | {
                    enabled?: T;
                    preset?: T;
                    durationMs?: T;
                    delayMs?: T;
                  };
              seo?:
                | T
                | {
                    isPrimaryHeading?: T;
                    includeInTableOfContents?: T;
                    noIndexSection?: T;
                    structuredDataType?: T;
                  };
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              text?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              settings?: T;
              theme?:
                | T
                | {
                    background?: T;
                    colorMode?: T;
                    containerWidth?: T;
                    spacing?: T;
                  };
              visibility?:
                | T
                | {
                    field?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
              responsive?: T;
              animation?:
                | T
                | {
                    enabled?: T;
                    preset?: T;
                    durationMs?: T;
                    delayMs?: T;
                  };
              seo?:
                | T
                | {
                    isPrimaryHeading?: T;
                    includeInTableOfContents?: T;
                    noIndexSection?: T;
                    structuredDataType?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              headline?: T;
              text?: T;
              items?:
                | T
                | {
                    image?:
                      | T
                      | {
                          media?: T;
                          url?: T;
                          alt?: T;
                        };
                    title?: T;
                    description?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              settings?: T;
              theme?:
                | T
                | {
                    background?: T;
                    colorMode?: T;
                    containerWidth?: T;
                    spacing?: T;
                  };
              visibility?:
                | T
                | {
                    field?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
              responsive?: T;
              animation?:
                | T
                | {
                    enabled?: T;
                    preset?: T;
                    durationMs?: T;
                    delayMs?: T;
                  };
              seo?:
                | T
                | {
                    isPrimaryHeading?: T;
                    includeInTableOfContents?: T;
                    noIndexSection?: T;
                    structuredDataType?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statistics?:
          | T
          | {
              headline?: T;
              text?: T;
              animated?: T;
              items?:
                | T
                | {
                    value?: T;
                    suffix?: T;
                    label?: T;
                    id?: T;
                  };
              settings?: T;
              theme?:
                | T
                | {
                    background?: T;
                    colorMode?: T;
                    containerWidth?: T;
                    spacing?: T;
                  };
              visibility?:
                | T
                | {
                    field?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
              responsive?: T;
              animation?:
                | T
                | {
                    enabled?: T;
                    preset?: T;
                    durationMs?: T;
                    delayMs?: T;
                  };
              seo?:
                | T
                | {
                    isPrimaryHeading?: T;
                    includeInTableOfContents?: T;
                    noIndexSection?: T;
                    structuredDataType?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              headline?: T;
              text?: T;
              items?:
                | T
                | {
                    avatar?:
                      | T
                      | {
                          media?: T;
                          url?: T;
                          alt?: T;
                        };
                    rating?: T;
                    quote?: T;
                    name?: T;
                    company?: T;
                    id?: T;
                  };
              settings?: T;
              theme?:
                | T
                | {
                    background?: T;
                    colorMode?: T;
                    containerWidth?: T;
                    spacing?: T;
                  };
              visibility?:
                | T
                | {
                    field?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
              responsive?: T;
              animation?:
                | T
                | {
                    enabled?: T;
                    preset?: T;
                    durationMs?: T;
                    delayMs?: T;
                  };
              seo?:
                | T
                | {
                    isPrimaryHeading?: T;
                    includeInTableOfContents?: T;
                    noIndexSection?: T;
                    structuredDataType?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              headline?: T;
              text?: T;
              plans?:
                | T
                | {
                    name?: T;
                    description?: T;
                    price?: T;
                    highlighted?: T;
                    features?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    cta?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              settings?: T;
              theme?:
                | T
                | {
                    background?: T;
                    colorMode?: T;
                    containerWidth?: T;
                    spacing?: T;
                  };
              visibility?:
                | T
                | {
                    field?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
              responsive?: T;
              animation?:
                | T
                | {
                    enabled?: T;
                    preset?: T;
                    durationMs?: T;
                    delayMs?: T;
                  };
              seo?:
                | T
                | {
                    isPrimaryHeading?: T;
                    includeInTableOfContents?: T;
                    noIndexSection?: T;
                    structuredDataType?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              headline?: T;
              text?: T;
              categoriesEnabled?: T;
              items?:
                | T
                | {
                    category?: T;
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              settings?: T;
              theme?:
                | T
                | {
                    background?: T;
                    colorMode?: T;
                    containerWidth?: T;
                    spacing?: T;
                  };
              visibility?:
                | T
                | {
                    field?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
              responsive?: T;
              animation?:
                | T
                | {
                    enabled?: T;
                    preset?: T;
                    durationMs?: T;
                    delayMs?: T;
                  };
              seo?:
                | T
                | {
                    isPrimaryHeading?: T;
                    includeInTableOfContents?: T;
                    noIndexSection?: T;
                    structuredDataType?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              backgroundVariant?: T;
              headline?: T;
              text?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              settings?: T;
              theme?:
                | T
                | {
                    background?: T;
                    colorMode?: T;
                    containerWidth?: T;
                    spacing?: T;
                  };
              visibility?:
                | T
                | {
                    field?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
              responsive?: T;
              animation?:
                | T
                | {
                    enabled?: T;
                    preset?: T;
                    durationMs?: T;
                    delayMs?: T;
                  };
              seo?:
                | T
                | {
                    isPrimaryHeading?: T;
                    includeInTableOfContents?: T;
                    noIndexSection?: T;
                    structuredDataType?: T;
                  };
              id?: T;
              blockName?: T;
            };
        footer?:
          | T
          | {
              logo?:
                | T
                | {
                    media?: T;
                    url?: T;
                    alt?: T;
                  };
              navigation?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              socialLinks?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              copyright?: T;
              contact?: T;
              settings?: T;
              theme?:
                | T
                | {
                    background?: T;
                    colorMode?: T;
                    containerWidth?: T;
                    spacing?: T;
                  };
              visibility?:
                | T
                | {
                    field?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
              responsive?: T;
              animation?:
                | T
                | {
                    enabled?: T;
                    preset?: T;
                    durationMs?: T;
                    delayMs?: T;
                  };
              seo?:
                | T
                | {
                    isPrimaryHeading?: T;
                    includeInTableOfContents?: T;
                    noIndexSection?: T;
                    structuredDataType?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              headline?: T;
              text?: T;
              email?: T;
              phone?: T;
              formId?: T;
              settings?: T;
              theme?:
                | T
                | {
                    background?: T;
                    colorMode?: T;
                    containerWidth?: T;
                    spacing?: T;
                  };
              visibility?:
                | T
                | {
                    field?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
              responsive?: T;
              animation?:
                | T
                | {
                    enabled?: T;
                    preset?: T;
                    durationMs?: T;
                    delayMs?: T;
                  };
              seo?:
                | T
                | {
                    isPrimaryHeading?: T;
                    includeInTableOfContents?: T;
                    noIndexSection?: T;
                    structuredDataType?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  organizationId?: T;
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  categories?: T;
  tags?: T;
  readingTime?: T;
  relatedPosts?: T;
  publishDate?: T;
  scheduledPublishAt?: T;
  previewUrl?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        socialImage?: T;
        openGraph?:
          | T
          | {
              title?: T;
              description?: T;
              type?: T;
            };
        twitterCard?: T;
        robots?:
          | T
          | {
              index?: T;
              follow?: T;
            };
        schema?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  organizationId?: T;
  name?: T;
  slug?: T;
  description?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        socialImage?: T;
        openGraph?:
          | T
          | {
              title?: T;
              description?: T;
              type?: T;
            };
        twitterCard?: T;
        robots?:
          | T
          | {
              index?: T;
              follow?: T;
            };
        schema?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  organizationId?: T;
  name?: T;
  slug?: T;
  description?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        socialImage?: T;
        openGraph?:
          | T
          | {
              title?: T;
              description?: T;
              type?: T;
            };
        twitterCard?: T;
        robots?:
          | T
          | {
              index?: T;
              follow?: T;
            };
        schema?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  organizationId?: T;
  name?: T;
  slug?: T;
  email?: T;
  userId?: T;
  avatar?: T;
  bio?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  organizationId?: T;
  alt?: T;
  caption?: T;
  folderPath?: T;
  focalPoint?:
    | T
    | {
        x?: T;
        y?: T;
      };
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  organizationId?: T;
  title?: T;
  slug?: T;
  location?: T;
  items?:
    | T
    | {
        label?: T;
        url?: T;
        page?: T;
        openInNewTab?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              page?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  organizationId?: T;
  from?: T;
  to?: T;
  statusCode?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  organizationId?: T;
  siteName?: T;
  seo?:
    | T
    | {
        siteTitle?: T;
        titleTemplate?: T;
        defaultMetaDescription?: T;
        canonicalBaseUrl?: T;
        defaultOgImage?: T;
        siteName?: T;
        locale?: T;
        defaultRobots?:
          | T
          | {
              index?: T;
              follow?: T;
            };
      };
  brand?:
    | T
    | {
        logo?: T;
        favicon?: T;
        tagline?: T;
      };
  theme?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        fontFamily?: T;
        borderRadius?: T;
        containerWidth?: T;
        mode?: T;
      };
  contactInformation?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  analytics?:
    | T
    | {
        googleAnalyticsId?: T;
        googleTagManagerId?: T;
        metaPixelId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-settings".
 */
export interface PlatformSetting {
  id: number;
  agencyName: string;
  defaultBrand?: {
    logo?: (number | null) | Media;
    favicon?: (number | null) | Media;
  };
  theme?: {
    primaryColor?: string | null;
    secondaryColor?: string | null;
    fontFamily?: string | null;
    borderRadius?: string | null;
    containerWidth?: string | null;
    mode?: ('system' | 'light' | 'dark') | null;
  };
  defaultAnalytics?: {
    googleAnalyticsId?: string | null;
    googleTagManagerId?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-settings_select".
 */
export interface PlatformSettingsSelect<T extends boolean = true> {
  agencyName?: T;
  defaultBrand?:
    | T
    | {
        logo?: T;
        favicon?: T;
      };
  theme?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        fontFamily?: T;
        borderRadius?: T;
        containerWidth?: T;
        mode?: T;
      };
  defaultAnalytics?:
    | T
    | {
        googleAnalyticsId?: T;
        googleTagManagerId?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | CmsUser;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}